#!/bin/bash

# Load color and icon definitions
source "$HOME/.config/sketchybar/colors.sh"
source "$HOME/.config/sketchybar/icons.sh"

# Directories for item and plugin configurations
ITEM_DIR="$HOME/.config/sketchybar/items"
PLUGIN_DIR="$HOME/.config/sketchybar/plugins"

# Font configuration (requires specific font variants)
FONT="SF Pro"
PADDINGS=3 # Uniform padding value for icon, label, and background elements

# Setting up and starting the helper process
HELPER="git.felix.helper"
pkill helper  # Kill any existing helper processes
cd "$HOME/.config/sketchybar/helper" && make  # Rebuild the helper process
"$HOME/.config/sketchybar/helper/helper" "$HELPER" > /dev/null 2>&1 &

# Unload macOS on-screen display (OSD) for volume changes
launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist > /dev/null 2>&1 &

# Configure general appearance of the bar
bar=(
  height=32
  color="$BAR_COLOR"
  shadow=on
  position=top
  sticky=on
  padding_right=8
  padding_left=8
  corner_radius=8
  y_offset=6
  margin=8
  blur_radius=20
  notch_width=0
)

# Apply bar configuration
sketchybar --bar "${bar[@]}"

# Set up default values for items
defaults=(
  updates=when_shown
  icon.font="$FONT:Bold:14.0"
  icon.color="$ICON_COLOR"
  icon.padding_left="$PADDINGS"
  icon.padding_right="$PADDINGS"
  label.font="$FONT:Semibold:13.0"
  label.color="$LABEL_COLOR"
  label.padding_left="$PADDINGS"
  label.padding_right="$PADDINGS"
  padding_right="$PADDINGS"
  padding_left="$PADDINGS"
  background.height=30
  background.corner_radius=9
  popup.background.border_width=2
  popup.background.corner_radius=9
  popup.background.border_color="$POPUP_BORDER_COLOR"
  popup.background.color="$POPUP_BACKGROUND_COLOR"
  popup.blur_radius=20
  popup.background.shadow.drawing=on
)

# Apply default item configuration
sketchybar --default "${defaults[@]}"

# Load item scripts for different sections of the bar

# Left section items
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

# Center section items
source "$ITEM_DIR/spotify.sh"

# Right section items
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/brew.sh"
source "$ITEM_DIR/github.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/cpu.sh"

# Force update all items (use cautiously, only in sketchybarrc)
sketchybar --update

echo "Sketchybar configuration loaded."
